### ISSUE TITLE
不能使用了

### ISSUE THREAD

**Issue by CKylinMC** [TaRGroup/CoolApk-Console#12]
```
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at com.targroup.coolapkconsole.activities.MainActivity$a.a(Unknown Source)
	at com.targroup.coolapkconsole.activities.MainActivity$a.doInBackground(Unknown Source)
	at android.os.AsyncTask$2.call(AsyncTask.java:316)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:255)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:776)

```
出现了错误，而且很多人都遇到了:hushed:

**Comment by Rachel030219** [comment]
抱歉，因为开发者都是学生所以…
我这边是能够正常用，不知道原因
请尝试去掉混淆自编译并将 log 发到下面，以方便我们调试

**Comment by duangsuse** [comment]
@Rachel030219 现在AS好像可以加载 _proguard_ 的 Map 了吧（?

**Comment by Rachel030219** [comment]
@duangsuse AS 3.0.1 嘛？
我这边更新了之后一直爆炸（
元旦回去看看好了

**Comment by CKylinMC** [comment]
emmm这个...十分抱歉，我不是做安卓程序的，不清楚去混淆之类的如何操作...因为看到酷安评论区那里很多很多反馈，而且我自己也遇到了，所以想反馈到这里希望可以更快被作者看到...

**Comment by Rachel030219** [comment]
@Cansll 是嘛……（捂脸
拖这么久了还没有解决十分抱歉，大概元旦期间我们会发出一个未混淆版的安装包，获得准确的错误日志之后就能解决这个问题了（

**Comment by CKylinMC** [comment]
嗯嗯。元旦快乐~

**Comment by Rachel030219** [comment]
抱歉 QAQ 元旦都没有时间
可能必须拖到寒假了…
总之 过年之前一定会把这个 bug 修掉（
（捂脸逃

**Comment by qqqwwweee123-ping** [comment]
谷歌商店下架了

**Comment by duangsuse** [comment]
> 谷歌商店下架了

嗯嗯，哪怕是这个 issue 都是一年多前的事情了

**Comment by CKylinMC** [comment]
@qqqwwweee123-ping 貌似这个项目已经停更掉了喔...

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Honor 8 发送_

**Comment by duangsuse** [comment]
> @qqqwwweee123-ping 貌似这个项目已经停更掉了喔...
> 
> _使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Honor 8 发送_

那就关了吧... FastHub 还加什么签名档... 这是要把 GitHub issue 区变成酷安么

**Comment by CKylinMC** [comment]
@duangsuse 小尴尬，重新下fasthub之后忘了关了...
